// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}], // We'll replace this

  // But you can create a sidebar manually
  docsSidebar: [ // This is the new name for your main sidebar

    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'doc', id: 'getting-started/introduction' },
      items: [
        'getting-started/introduction', // Assumes docs/getting-started/introduction.md
        'getting-started/quick-start',  // Assumes docs/getting-started/quick-start.md
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'core-concepts/architecture', // Assumes docs/core-concepts/architecture.md
        // Add more as you create them
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/configuration',    // Assumes docs/guides/configuration.md
        'guides/licensing',        // Assumes docs/guides/licensing.md
        'guides/skill-development',// Assumes docs/guides/skill-development.md
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: ['api-reference/process-endpoint'], // Assumes docs/api-reference/process-endpoint.md
    },
  ],
};

export default sidebars;
